//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/promise/all dijit/form/NumberTextBox dijit/form/Select dijit/form/TextBox dijit/form/DateTextBox dijit/form/TimeTextBox jimu/dijit/CheckBox jimu/dijit/URLInput jimu/dijit/DrawBox esri/SpatialReference esri/tasks/LinearUnit esri/tasks/FeatureSet esri/layers/FeatureLayer esri/tasks/query esri/tasks/QueryTask esri/request ../BaseEditor".split(" "),function(e,k,f,c,n,r,s,t,l,d,u,v,w,p,x,y,z,A,D,q,B,
C,g){d={};d.UnsupportEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-unsupport",postCreate:function(){this.inherited(arguments);c.setAttr(this.domNode,"innerHTML",this.message)},getValue:function(){return null}});d.ShowMessage=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-message",postCreate:function(){this.inherited(arguments);c.setAttr(this.domNode,"innerHTML",this.message)},getValue:function(){return null}});d.GeneralEditorWrapperEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-wrapper",
postCreate:function(){this.inherited(arguments);c.setStyle(this.gEditor.domNode,"width","100%");this.gEditor.placeAt(this.domNode)},getValue:function(){return this.gEditor.getValue()}});d.MultiValueChooser=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-multivalue-chooser",postCreate:function(){this.inherited(arguments);this.checkBoxs=[];f.forEach(this.param.choiceList,function(a){a=new w({label:a,checked:this.param.defaultValue&&-1<this.param.defaultValue.indexOf(a)?!0:!1});a.placeAt(this.domNode);
this.checkBoxs.push(a)},this)},getValue:function(){var a=[];f.forEach(this.checkBoxs,function(b){b.checked&&a.push(b.label)},this);return a}});d.MultiValueEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-multivalue",postCreate:function(){this.inherited(arguments);this.editors=[];var a=c.create("div",{"class":"input-list"},this.domNode),b=k.clone(this.param,a);b.dataType=this.param.dataType.substr(13,this.param.dataType.length);b.originParam=this.param;setTimeout(k.hitch(this,this._initChildEditors,
b,a),100);this._createAddInputNode(b,a)},_initChildEditors:function(a,b){this.param.defaultValue&&0<this.param.defaultValue.length?f.forEach(this.param.defaultValue,function(h){a.defaultValue=h;this._createSingleInputContainerNode(a,b)},this):(delete a.defaultValue,this._createSingleInputContainerNode(a,b))},getValue:function(){var a=[];f.forEach(this.editors,function(b){a.push(b.getValue())},this);return a},getGPValue:function(){var a=new r,b=[];f.forEach(this.editors,function(a){b.push(a.getGPValue())},
this);s(b).then(function(b){a.resolve(b)},function(b){a.reject(b)});return a},destroy:function(){f.forEach(this.editors,function(a){a.destroy()});this.editors=[];this.inherited(arguments)},_createSingleInputContainerNode:function(a,b){var h=c.create("div",{"class":"single-input"},b),m=this.editorManager.createEditor(a,"input",this.context),d=c.getContentBox(this.domNode).w-30-3;c.setStyle(m.domNode,{display:"inline-block",width:d+"px"});m.placeAt(h);this._createRemoveInputNode(h);h.inputEditor=m;
this.editors.push(m);return h},_createRemoveInputNode:function(a){var b=c.create("div",{"class":"remove",innerHTML:"-"},a);this.own(n(b,"click",k.hitch(this,function(){this.editors.splice(this.editors.indexOf(a.inputEditor),1);a.inputEditor.destroy();c.destroy(a)})));return b},_createAddInputNode:function(a,b){var h=c.create("div",{"class":"add-input"},this.domNode),d=c.create("div",{"class":"add-btn",innerHTML:"+"},h);this.own(n(d,"click",k.hitch(this,function(){this._createSingleInputContainerNode(a,
b)})));return h}});d.LinerUnitEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-liner-unit",postCreate:function(){this.inherited(arguments);this.distance=void 0===this.param.defaultValue?"":this.param.defaultValue.distance;this.units=void 0===this.param.defaultValue?"":this.param.defaultValue.units;void 0===this.distance&&(this.distance=0);void 0===this.units&&(this.units="esriMeters");this.inputDijit=new t({value:this.distance});this.selectDijit=new l({value:this.units,options:[{label:"Meters",
value:"esriMeters"},{label:"Kilometers",value:"esriKilometers"},{label:"Feet",value:"esriFeet"},{label:"Miles",value:"esriMiles"},{label:"NauticalMiles",value:"esriNauticalMiles"},{label:"Yards",value:"esriYards"}]});this.inputDijit.placeAt(this.domNode);this.selectDijit.placeAt(this.domNode)},getValue:function(){var a=new z;a.distance=this.inputDijit.getValue();a.units=this.selectDijit.getValue();return a}});d.DateTimeEditor=e(g,{baseClass:"jimu-gp-editor-base jimu-gp-editor-datatime",postCreate:function(){this.value=
this.param.defaultValue?new Date(this.param.defaultValue):new Date;this.inherited(arguments);this.dateDijit=new u({value:this.value,style:{width:"60%"}});this.timeDijit=new v({value:this.value,style:{width:"40%"}});this.dateDijit.placeAt(this.domNode);this.timeDijit.placeAt(this.domNode)},getValue:function(){var a=new Date,b=this.dateDijit.getValue(),c=this.timeDijit.getValue();a.setFullYear(b.getFullYear());a.setMonth(b.getMonth());a.setDate(b.getDate());a.setHours(c.getHours());a.setMinutes(c.getMinutes());
a.setSeconds(c.getSeconds());return a.getTime()}});d.SelectFeatureSetFromDraw=e([g,x],{constructor:function(a){this.drawLayerId=a.param.name},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-draw");c.addClass(this.domNode,"jimu-gp-editor-base");this.startup()},onDrawEnd:function(a){this.graphic=a},onClear:function(){this.graphic=null},getValue:function(){if(this.graphic){var a=new A;a.features=[this.graphic];return a}return null}});d.SelectFeatureSetFromLayer=
e([g,l],{postCreate:function(){this.options=[];f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);if("esri.layers.FeatureLayer"===a.declaredClass&&(!this.geometryType||a.geometryType===this.geometryType))this.options.push({label:a.label||a.title||a.name||a.id,value:a.id})},this);this.inherited(arguments);this.setValue(this.value);c.addClass(this.domNode,"jimu-gp-editor-sffl");c.addClass(this.domNode,"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a=
new q;a.where="1\x3d1";return this.map.getLayer(this.value).queryFeatures(a)}});d.GetUrlObjectFromLayer=e([g,l],{postCreate:function(){this.options=[];f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);if("esri.layers.FeatureLayer"===a.declaredClass&&(!this.geometryType||a.geometryType===this.geometryType))this.options.push({label:a.label||a.title||a.name||a.id,value:a.id})},this);this.inherited(arguments);this.setValue(this.value);c.addClass(this.domNode,"jimu-gp-editor-sffl");
c.addClass(this.domNode,"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a,b;f.forEach(this.map.graphicsLayerIds,function(b){var c=this.map.getLayer(b);b===this.getValue()&&(a=c.url)},this);b={url:a};b=this.wrapGPValue(b);return this.wrapValueToDeferred(b)}});d.SelectFeatureSetFromUrl=e([g,p],{postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-sffu");c.addClass(this.domNode,"jimu-gp-editor-base");this.queryTask=new B(this.value)},
getValue:function(){return this.value},getGPValue:function(){var a=new q;a.where="1\x3d1";a.returnGeometry=!0;a.outFields=f.map(this.querySetting.fields,function(a){return a.name},this);a.outSpatialReference=new y(this.querySetting.spatialReference.wkid);return this.queryTask.execute(a)}});d.ObjectUrlEditor=e([g,p],{postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-gp-editor-ourl");c.addClass(this.domNode,"jimu-gp-editor-base")},getValue:function(){return this.value},getGPValue:function(){var a=
{url:this.getValue()},a=this.wrapGPValue(a);return this.wrapValueToDeferred(a)}});d.LayerFieldChooser=e([g,l],{postCreate:function(){this.options=[];this.inherited(arguments);this.setValue(this.value);c.addClass(this.domNode,"jimu-gp-editor-lfc");c.addClass(this.domNode,"jimu-gp-editor-base")},update:function(a){this.inherited(arguments);var b=[],c;this.set("options",[]);this.set("value","");f.some(this.map.graphicsLayerIds,function(b){if(b===a)return c=this.map.getLayer(a),!0},this);c&&this._requestLayerInfo(c.url).then(k.hitch(this,
function(a){a&&a.fields&&(a=f.filter(a.fields,function(a){return"esriFieldTypeOID"!==a.type&&"esriFieldTypeGeometry"!==a.type}),b=f.map(a,function(a){return{label:a.alias||a.name,value:a.name}},this),this.set("options",b))}))},_requestLayerInfo:function(a){return C({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"})}});return d});