//>>built
(function(e){var m=e.HTMLCanvasElement&&e.HTMLCanvasElement.prototype,c;if(c=e.Blob)try{c=Boolean(new Blob)}catch(q){c=!1}var p=c;if(c=p)if(c=e.Uint8Array)try{c=100===(new Blob([new Uint8Array(100)])).size}catch(u){c=!1}var n=c,h=e.BlobBuilder||e.WebKitBlobBuilder||e.MozBlobBuilder||e.MSBlobBuilder,g=(p||h)&&e.atob&&e.ArrayBuffer&&e.Uint8Array&&function(a){var b,c,d,g;b=0<=a.split(",")[0].indexOf("base64")?atob(a.split(",")[1]):decodeURIComponent(a.split(",")[1]);c=new ArrayBuffer(b.length);d=new Uint8Array(c);
for(g=0;g<b.length;g+=1)d[g]=b.charCodeAt(g);a=a.split(",")[0].split(":")[1].split(";")[0];if(p)return new Blob([n?d:c],{type:a});d=new h;d.append(c);return d.getBlob(a)};e.HTMLCanvasElement&&!m.toBlob&&(m.mozGetAsFile?m.toBlob=function(a,b,c){c&&m.toDataURL&&g?a(g(this.toDataURL(b,c))):a(this.mozGetAsFile("blob",b))}:m.toDataURL&&g&&(m.toBlob=function(a,b,c){a(g(this.toDataURL(b,c)))}));e.dataURLtoBlob=g})(window);
(function(e,m){function c(k,a,f,b,c){k={type:f.type||f,target:k,result:b};F(k,c);a(k)}function q(k,a,f,b){if(l.isBlob(k)&&z&&z.prototype["readAs"+f]){var d=new z;M(d,U,function ba(f){var b=f.type;"progress"==b?c(k,a,f,f.target.result,{loaded:f.loaded,total:f.total}):"loadend"==b?(I(d,U,ba),d=null):c(k,a,f,f.target.result)});try{if(b)d["readAs"+f](k,b);else d["readAs"+f](k)}catch(G){c(k,a,"error",m,{error:G.toString()})}}else c(k,a,"error",m,{error:"filreader_not_support_"+f})}function p(k){return k&&
(v&&k instanceof v||k.blob||k.image&&k.file||k.flashId)}function u(k,a){if(!k.type&&0===k.size%4096&&102400>=k.size)if(z)try{var f=new z;V(f,U,function(k){k="error"!=k.type;a(k);k&&f.abort()});f.readAsDataURL(k)}catch(b){a(!1)}else a(null);else a(!0)}function n(k){var a;k.getAsEntry?a=k.getAsEntry():k.webkitGetAsEntry&&(a=k.webkitGetAsEntry());return a}function h(k,a){if(k)if(k.isFile)k.file(function(f){f.fullPath=k.fullPath;a(!1,[f])},function(k){a("FileError.code: "+k.code)});else if(k.isDirectory){var f=
[];k.createReader().readEntries(function(k){l.afor(k,function(k,b){h(b,function(b,c){b?l.log(b):f=f.concat(c);k?k():a(!1,f)})})},function(k){a("directory_reader: "+k)})}else h(n(k),a);else a("invalid entry")}function g(k,a){var f=[],b={};if(W.test(k&&k.tagName)){var c=l.getFiles(k);b[k.name||a]=null!==k.getAttribute("multiple")?c:c[0]}else J(k)?W.test(k[0]&&k[0].tagName)?A(k,function(k){b[k.name||a]=l.getFiles(k)}):p(k[0])&&(b[a]=k):p(k)?b[a]=k:b=k;A(b,function ea(k,a){J(k)?A(k,function(k){ea(k,a)}):
p(k)&&f.push({name:a,file:k,size:k.size,total:k.size,loaded:0})});return f}function a(k,a,f){var b=new l.Form,c=l.queue(function(){f(b)}),d=l.support.transform&&k.imageTransform,g=d&&s(d),w=l.postNameConcat;A(a,function(a,f){var L=a.file,O=w(a.name,k.serial||k.chunkSize?null:f),s=L.name,e=L.type;(function fa(a){a.image?(c.inc(),a.toData(function(k,a){s=s||(new Date).getTime()+".png";fa(a);c.next()})):l.Image&&d&&(/^image/.test(a.type)||ga.test(a.nodeName))?(c.inc(),g&&(d=[].concat(d)),l.Image.transform(a,
d,k.imageAutoOrientation,function(f,L){if(g&&!f)!P&&!l.flashEngine&&(b.multipart=!0),b.append(O,L[0],s,d[0].type||e);else{var v=0;f||A(L,function(k,a){!P&&!l.flashEngine&&(b.multipart=!0);d[a].postName||(v=1);b.append(d[a].postName||w(O,a),k,s,d[a].type||e)});if(f||k.imageOriginal)b.append(w(O,v?"original":null),a,s,e)}c.next()})):s!==l.expando&&b.append(O,a,s)})(L)});A(k.data,function da(k,a){"object"==typeof k?A(k,function(k,f){da(k,w(a,f))}):b.append(a,k)});c.check()}function b(k){var a={};A(k,
function(k,f){k&&("object"===typeof k&&null==k.nodeType)&&(k=F({},k));a[f]=k});return a}function s(k){for(var a in k)if(k.hasOwnProperty(a)&&!(k[a]instanceof Object||"overlay"===a||"filter"===a))return!0;return!1}function d(k,a){var f=!1;if(C.msSaveBlob)f=C.msSaveBlob(k,a);else if(l.support.download){var b=l.createURL(k),c=y.body,d=y.createElement("a");b&&(d.href=b,d.download=a||k.name,d.style.top="-10000px",d.style.position="absolute",c.appendChild(d),d.click(),c.removeChild(d),f=!0,N(function(){l.revokeURL(b)},
1))}return f}var B=1,x=function(){},y=e.document,t=y.doctype||{},C=e.navigator,r=e.navigator.userAgent,f=e.createObjectURL&&e||e.URL&&URL.revokeObjectURL&&URL||e.webkitURL&&webkitURL,w=e.Blob,v=e.File,z=e.FileReader,E=e.FormData,D=e.jQuery,Q=e.XMLHttpRequest,H=!(!v||!z||!e.Uint8Array&&!E&&!Q.prototype.sendAsBinary)&&!(/safari\//i.test(r)&&!/chrome\//i.test(r)&&/windows/i.test(r)),r=H&&"withCredentials"in new Q,E=H&&!!w&&!(!w.prototype.webkitSlice&&!w.prototype.mozSlice&&!w.prototype.slice),P=e.dataURLtoBlob,
R=/img/i,ha=/canvas/i,ga=/img|canvas/i,W=/input/i,ia=/^data:[^,]+,/,S=e.Math,N=e.setTimeout,ja=e.clearTimeout,T=function(k){k=new e.Number(S.pow(1024,k));k.from=function(k){return S.round(k*this)};return k},K={},Y=[],U="abort progress error load loadend",ka="status statusText readyState response responseXML responseText responseBody".split(" "),J=function(k){return k&&"length"in k},A=function(k,a,f){if(k)if(J(k))for(var b=0,c=k.length;b<c;b++)b in k&&a.call(f,k[b],b,k);else for(b in k)k.hasOwnProperty(b)&&
a.call(f,k[b],b,k)},Z=function(k,a){for(var f=-1,b=k&&k.length;b--;)if(k[b]===a){f=b;break}return f},F=function(k){for(var a=arguments,f=1,b=function(a,f){k[f]=a};f<a.length;f++)A(a[f],b);return k},M=function(k,a,f){if(k){var b=l.uid(k);K[b]||(K[b]={});var c=z&&k&&k instanceof z;A(a.split(/\s+/),function(a){D&&!c?D.event.add(k,a,f):(K[b][a]||(K[b][a]=[]),K[b][a].push(f),k.addEventListener?k.addEventListener(a,f,!1):k.attachEvent?k.attachEvent("on"+a,f):k["on"+a]=f)})}},I=function(a,f,b){if(a){var c=
l.uid(a),d=K[c]||{},w=z&&a&&a instanceof z;A(f.split(/\s+/),function(f){if(D&&!w)D.event.remove(a,f,b);else{for(var c=d[f]||[],g=c.length;g--;)if(c[g]===b){c.splice(g,1);break}a.addEventListener?a.removeEventListener(f,b,!1):a.detachEvent?a.detachEvent("on"+f,b):a["on"+f]=null}})}},V=function(a,f,b){M(a,f,function aa(c){I(a,f,aa);b(c)})},X=function(a){a.target||(a.target=e.event&&e.event.srcElement||y);3===a.target.nodeType&&(a.target=a.target.parentNode);return a},$=function(a){var f=y.createElement("input");
f.setAttribute("type","file");return a in f},l={version:"2.1.0",cors:!1,html5:!0,media:!1,formData:!0,multiPassResize:!0,debug:!1,pingUrl:!1,multiFlash:!1,flashAbortTimeout:0,withCredentials:!0,staticPath:"./stemapp/libs/polyfills/fileAPI/",flashUrl:0,flashImageUrl:0,postNameConcat:function(a,f){return a+(null!=f?"["+f+"]":"")},support:{dnd:r&&"ondrop"in y.createElement("div"),cors:r,html5:H,chunked:E,dataURI:!0,accept:$("accept"),multiple:$("multiple"),saveAs:!!C.msSaveBlob,download:"download"in
y.createElement("a")},ext2mime:{jpg:"image/jpeg",tif:"image/tiff",txt:"text/plain"},accept:{"image/*":"art bm bmp dwg dxf cbr cbz fif fpx gif ico iefs jfif jpe jpeg jpg jps jut mcf nap nif pbm pcx pgm pict pm png pnm qif qtif ras rast rf rp svf tga tif tiff xbm xbm xpm xwd","audio/*":"m4a flac aac rm mpa wav wma ogg mp3 mp2 m3u mod amf dmf dsm far gdm imf it m15 med okt s3m stm sfx ult uni xm sid ac3 dts cue aif aiff wpl ape mac mpc mpp shn wv nsf spc gym adplug adx dsp adp ymf ast afc hps xs","video/*":"m4v 3gp nsv ts ty strm rm rmvb m3u ifo mov qt divx xvid bivx vob nrg img iso pva wmv asf asx ogm m2v avi bin dat dvr-ms mpg mpeg mp4 mkv avc vp3 svq3 nuv viv dv fli flv wpl"},
uploadRetry:0,networkDownRetryTimeout:5E3,chunkSize:0,chunkUploadRetry:0,chunkNetworkDownRetryTimeout:2E3,KB:T(1),MB:T(2),GB:T(3),TB:T(4),EMPTY_PNG:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVQIW2NkAAIAAAoAAggA9GkAAAAASUVORK5CYII\x3d",expando:"fileapi"+(new Date).getTime(),uid:function(a){return a?a[l.expando]=a[l.expando]||l.uid():(++B,l.expando+B)},log:function(){l.debug&&(e.console&&console.log)&&(console.log.apply?console.log.apply(console,arguments):console.log([].join.call(arguments,
" ")))},newImage:function(a,f){var b=y.createElement("img");if(f)l.event.one(b,"error load",function(a){f("error"==a.type,b);b=null});b.src=a;return b},getXHR:function(){var a;if(Q)a=new Q;else if(e.ActiveXObject)try{a=new ActiveXObject("MSXML2.XMLHttp.3.0")}catch(f){a=new ActiveXObject("Microsoft.XMLHTTP")}return a},createURL:function(a){return f?f.createObjectURL(a):null},revokeURL:function(a){return f&&f.revokeObjectURL(a)},isArray:J,event:{on:M,off:I,one:V,fix:X},throttle:function(a,f){var b,
c;return function(){c=arguments;b||(a.apply(e,c),b=N(function(){b=0;a.apply(e,c)},f))}},F:x,parseJSON:function(a){var f;try{f=e.JSON&&JSON.parse?JSON.parse(a):(new Function("return ("+a.replace(/([\r\n])/g,"\\$1")+");"))()}catch(b){l.log("[err] FileAPI.parseJSON: "+b)}return f},trim:function(a){a=String(a);return a.trim?a.trim():a.replace(/^\s+|\s+$/g,"")},defer:function(){var a=[],f=[],b=[],c=function(b,c){c&&(b?a:f).push(c);return this},d=function(g,w){var s=g?a:f,e=0,v=s.length;c=function(a,k){a===
g&&k.apply(this,w)};d=x;a=f=null;for(b=[];e<v;e++)s[e]&&s[e].apply(this,w)};return{done:function(a){c(1,a);return this},fail:function(a){c(0,a);return this},resolve:function(){d(1,arguments);return this},reject:function(){d(0,arguments);return this},notify:function(){for(var a=0,k=b.length;a<k;a++)b[a].apply(this,arguments)},progress:function(a){a&&b.push(a);return this},then:function(a,k){return this.done(a).fail(k)},always:function(a){return this.then(a,a)},promise:function(){return this}}},queue:function(a){var f=
0,b=0,c=!1,d=!1,g={inc:function(){b++},next:function(){f++;N(g.check,0)},check:function(){f>=b&&!c&&g.end()},isFail:function(){return c},fail:function(){!c&&a(c=!0)},end:function(){d||(d=!0,a())}};return g},each:A,indexOf:Z,afor:function(a,f){var b=0,c=a.length;J(a)&&c--?function G(){f(c!=b&&G,a[b],b++)}():f(!1)},extend:F,isFile:function(a){return H&&a&&(a instanceof v||a instanceof w)},isBlob:function(a){return H&&a&&a instanceof w},isCanvas:function(a){return a&&ha.test(a.nodeName)},getFilesFilter:function(a){return(a=
"string"==typeof a?a:a.getAttribute&&a.getAttribute("accept")||"")?RegExp("("+a.replace(/\./g,"\\.").replace(/,/g,"|")+")$","i"):/./},readAsDataURL:function(a,f){l.isCanvas(a)?c(a,f,"load",l.toDataURL(a)):q(a,f,"DataURL")},readAsBinaryString:function(a,f){z&&z.prototype.readAsBinaryString?q(a,f,"BinaryString"):l.readAsDataURL(a,function(a){if("load"==a.type)try{a.result=l.toBinaryString(a.result)}catch(k){a.type="error",a.message=k.toString()}f(a)})},readAsArrayBuffer:function(a,f){q(a,f,"ArrayBuffer")},
readAsText:function(a,f,b){b||(b=f,f="utf-8");q(a,b,"Text",f)},toDataURL:function(a,f){if("string"==typeof a)return a;if(a.toDataURL)return a.toDataURL(f||"image/png")},toBinaryString:function(a){return e.atob(l.toDataURL(a).replace(ia,""))},readAsImage:function(a,b,d){if(l.isFile(a))if(f){var g=l.createURL(a);g?l.readAsImage(g,b,d):c(a,b,"error")}else l.readAsDataURL(a,function(f){"load"==f.type?l.readAsImage(f.result,b,d):(d||"error"==f.type)&&c(a,b,f,null,{loaded:f.loaded,total:f.total})});else l.isCanvas(a)?
c(a,b,"load",a):R.test(a.nodeName)?a.complete?c(a,b,"load",a):V(a,"error abort load",function G(d){"load"==d.type&&f&&l.revokeURL(a.src);I(a,"error abort load",G);c(a,b,d,a)}):a.iframe?c(a,b,{type:"error",message:"is iframe"}):(g=l.newImage(a.dataURL||a),l.readAsImage(g,b,d))},getMimeType:function(a){a=a&&(a.type||String(a.name||a).split(".").pop());var f=l.accept,b,c;if(!/^[^/]+\/[^/]+$/.test(a))for(c in f)if(b=RegExp(f[c].replace(/\s/g,"|"),"i"),b.test(a)||l.ext2mime[a]){a=l.ext2mime[a]||c.split("/")[0]+
"/"+a;break}return a},getDropFiles:function(a,f){var b=[],c=(a.originalEvent||a||"").dataTransfer||{},d=J(c.items)&&c.items[0]&&n(c.items[0]),g=l.queue(function(){f(b)});A((d?c.items:c.files)||[],function(a){g.inc();try{d?h(a,function(a,f){a?l.log("[err] getDropFiles:",a):b.push.apply(b,f);g.next()}):u(a,function(f){f&&b.push(a);g.next()})}catch(f){g.next(),l.log("[err] getDropFiles: ",f)}});g.check()},getFiles:function(a,f,b){var c=[];if(b)return l.filterFiles(l.getFiles(a),f,b),null;a.jquery&&(a.each(function(){c=
c.concat(l.getFiles(this))}),a=c,c=[]);"string"==typeof f&&(f=l.getFilesFilter(f));a.originalEvent?a=X(a.originalEvent):a.srcElement&&(a=X(a));a.dataTransfer?a=a.dataTransfer:a.target&&(a=a.target);a.files?(c=a.files,H||(c[0].blob=a,c[0].iframe=!0)):!H&&W.test(a&&a.tagName)?l.trim(a.value)&&(c=[{name:(a.value+"").split(/\\|\//g).pop(),type:l.getMimeType(a.value)}],c[0].blob=a,c[0].iframe=!0):J(a)&&(c=a);return l.filter(c,function(a){return!f||f.test(a.name)})},getTotalSize:function(a){for(var f=0,
b=a&&a.length;b--;)f+=a[b].size;return f},getInfo:function(a,f){var b={},c=Y.concat();l.isFile(a)?function G(){var d=c.shift();d?d.test(l.getMimeType(a))?d(a,function(a,c){a?f(a):(F(b,c),G())}):G():f(!1,b)}():f("not_support_info",b)},addInfoReader:function(a,f){f.test=function(f){return a.test(f)};Y.push(f)},filter:function(a,f){for(var b=[],c=0,d=a.length,g;c<d;c++)c in a&&(g=a[c],f.call(g,g,c,a)&&b.push(g));return b},filterFiles:function(a,f,b){if(a.length){var c=a.concat(),d,g=[],w=[];(function ca(){c.length?
(d=c.shift(),l.getInfo(d,function(a,b){(f(d,a?!1:b)?g:w).push(d);ca()})):b(g,w)})()}else b([],a)},upload:function(f,c,d){function w(){for(var a=0,f=m.length,b;f--;)b=m[f],a+=b.size*(b.loaded/b.total);return a}function s(){var f=v.splice(0,z?1:1E5),c=z?f[0]&&f[0].file:e.files,k=l.getTotalSize(f),g=!1,r=b(d);f.loaded=0;f.size=f.total=k;m.push(f);y&&(c=null,l.log("[warn] FileAPI.upload() \u2014 called without files"));("abort"!=e.statusText||e.current)&&(f.length||y)?(y=!1,t++,(e.currentFile=c)&&!1===
d.prepare(c,r)?s():(r.file=c,a(r,f,function(a){B||d.upload(e,d);var b=new l.XHR(F({},r,{upload:c?function(){z&&(p.push(c),b.activeFiles=p,d.fileupload(c,b,r))}:x,progress:c?function(a){g||(g=a.loaded==a.total,f.total=a.total,f.loaded=S.min(a.loaded,a.total),(z||q)&&d.fileprogress({type:"progress",total:f.total,loaded:f.loaded},c,b,r),h.notify({type:"progress",total:n,loaded:e.loaded=w()},c,b,r))}:x,complete:function(a){A(ka,function(a){e[a]=b[a]});c&&(f.total=f.total||f.size,f.loaded=f.total,this.progress(f),
g=!0,e.loaded=B=w(),z&&(p.splice(Z(p,c),1),d.filecomplete(a,b,c,r)));t--;N(function(){s()},0)}}));e.abort=function(a){a||(v.length=0);this.current=a;b.abort()};b.send(a)}))):t||((k=200==e.status||201==e.status||204==e.status?!1:e.statusText||"error")?h.reject(k,e,d):h.resolve(e,d),d.complete(k,e,d))}d=c||"string"==typeof f?F({},d,{url:f,files:[].concat(c)}):f;d=F({jsonp:"callback",prepare:x,beforeupload:x,upload:x,fileupload:x,fileprogress:x,filecomplete:x,progress:x,complete:x,pause:x,serial:!0,
parallel:0,postName:"files",chunkSize:l.chunkSize,imageOriginal:!0,chunkUploadRetry:l.chunkUploadRetry,uploadRetry:l.uploadRetry},d);d.serial||(d.chunkSize&&(d.chunkSize=0,l.log("[warn] FileAPI.upload: `chunkSize \x3e 0` is not supported, if serial \x3d\x3d false")),l.flashEngine&&l.log("[warn] FileAPI.upload: `serial \x3d\x3d false` is not supported in Flash."));0<d.parallel&&(d.serial=!0,l.flashEngine&&l.log("[warn] FileAPI.upload: `parallel \x3e 0` is not supported in Flash."));d.imageAutoOrientation&&
!d.imageTransform&&(d.imageTransform={rotate:"auto"});var e=new l.XHR(d),v=g(d.files,d.postName),h=l.defer(),r=this,n=0,B=0,t=0,z=H&&d.serial,q=z&&d.parallel,y=!v.length,m=[],p=e.activeFiles=[];A(v,function(a){n+=a.size});e.files=[];A(v,function(a){e.files.push(a.file)});e.total=n;e.loaded=0;e.filesLeft=v.length;d.beforeupload(e,d);h.progress(d.progress);h.done(d.success);h.fail(d.error);N(function(){for(var a=0;a<S.max(q,1);a++)s()},0);e.append=function(a,f){a=l._getFilesDataArray([].concat(a));
A(a,function(a){n+=a.size;e.files.push(a.file);f?v.unshift(a):v.push(a)});e.statusText="";t||s.call(r)};e.remove=function(a){for(var f=v.length,b;f--;)v[f].file==a&&(b=v.splice(f,1),n-=b.size);return b};e.error=h.fail;e.success=h.done;return F(e,h)},reset:function(a,f){var b,c;D?(c=D(a).clone(!0).insertBefore(a).val("")[0],f||D(a).remove()):(b=a.parentNode,c=b.insertBefore(a.cloneNode(!0),a),c.value="",f||b.removeChild(a),A(K[l.uid(a)],function(f,b){A(f,function(f){I(a,b,f);M(c,b,f)})}));return c},
load:function(f,b){var c=new l.XHR(b=F(b||{},{url:f,type:"GET",cache:!0,responseType:"blob"})),d=c.defer.resolve;c.defer.resolve=function(a,f){var b=a.response;return b&&w&&b instanceof w?d(b,a,f):a.defer.reject("load_not_supported",a,f)};a(b,[],function(a){c.send(a)});return c},saveAs:function(a,f){var b=l.defer();if("string"===typeof a)f===m&&(f=a.split("/").pop()),l.load(a).progress(b.notify).done(function(a){l.saveAs(a,f).then(b.resolve,b.reject)}).fail(b.reject);else try{d(a,f)?b.resolve():b.reject("saveAs_not_support")}catch(c){l.log("[err] FileAPI.saveAs: "+
c.toString()),b.reject(c)}return b}};l.addInfoReader(/^image/,function(a,f){if(!a.__dimensions){var b=a.__dimensions=l.defer();l.readAsImage(a,function(a){var f=a.target;b.resolve("load"==a.type?!1:"error",{width:f.width,height:f.height});f.src=l.EMPTY_PNG})}a.__dimensions.then(f)});l.event.dnd=function(a,f,b){var c,d;b||(b=f,f=x);z?(M(a,"dragenter dragleave dragover",function(a){for(var b=((a.originalEvent||a||"").dataTransfer||{}).types,k=b&&b.length,g=!1;k--;)if(~b[k].indexOf("File")){a.preventDefault();
d!==a.type&&(d=a.type,"dragleave"!=d&&f.call(a.currentTarget,!0,a),g=!0);break}g&&(ja(c),c=N(function(){f.call(a.currentTarget,"dragleave"!=d,a)},50))}),M(a,"drop",function(a){a.preventDefault();d=0;f.call(a.currentTarget,!1,a);l.getDropFiles(a,function(f){b.call(a.currentTarget,f,a)})})):l.log("Drag'n'Drop -- not supported")};l.event.dnd.off=function(a,f,b){I(a,"dragenter dragleave dragover",f);I(a,"drop",b)};D&&!D.fn.dnd&&(D.fn.dnd=function(a,f){return this.each(function(){l.event.dnd(this,a,f)})},
D.fn.offdnd=function(a,f){return this.each(function(){l.event.dnd.off(this,a,f)})});e.FileAPI=F(l,e.FileAPI);l.log("FileAPI: "+l.version);l.log("protocol: "+e.location.protocol);l.log("doctype: ["+t.name+"] "+t.publicId+" "+t.systemId);A(y.getElementsByTagName("meta"),function(a){/x-ua-compatible/i.test(a.getAttribute("http-equiv"))&&l.log("meta.http-equiv: "+a.getAttribute("content"))});l.flashUrl||(l.flashUrl=l.staticPath+"FileAPI.flash.swf");l.flashImageUrl||(l.flashImageUrl=l.staticPath+"FileAPI.flash.image.swf");
l.flashWebcamUrl||(l.flashWebcamUrl=l.staticPath+"FileAPI.flash.camera.swf")})(window,void 0);
(function(e,m,c){function q(a){if(a instanceof q){var b=new q(a.file);e.extend(b.matrix,a.matrix);return b}if(!(this instanceof q))return new q(a);this.file=a;this.size=a.size||100;this.matrix={sx:0,sy:0,sw:0,sh:0,dx:0,dy:0,dw:0,dh:0,resize:0,deg:0,quality:1,filter:0,multipass:e.multiPassResize}}var p=Math.min,u=Math.round,n=!1,h={8:270,3:180,6:90};try{n=-1<m.createElement("canvas").toDataURL("image/png").indexOf("data:image/png")}catch(g){}q.prototype={image:!0,constructor:q,set:function(a){e.extend(this.matrix,
a);return this},crop:function(a,b,g,d){g===c&&(g=a,d=b,a=b=0);return this.set({sx:a,sy:b,sw:g,sh:d||g})},resize:function(a,b,c){/min|max/.test(b)&&(c=b,b=a);return this.set({dw:a,dh:b||a,resize:c})},preview:function(a,b){return this.resize(a,b||a,"preview")},rotate:function(a){return this.set({deg:a})},filter:function(a){return this.set({filter:a})},overlay:function(a){return this.set({overlay:a})},clone:function(){return new q(this)},_load:function(a,b){var c=this;/img|video/i.test(a.nodeName)?b.call(c,
null,a):e.readAsImage(a,function(a){b.call(c,"load"!=a.type,a.result)})},_apply:function(a,b){var c=m.createElement("canvas"),d=this.getMatrix(a),g=c.getContext("2d"),h=d.deg,n=d.dw,t=d.dh,C=a.videoWidth||a.width,r=a.videoHeight||a.height,f=d.filter,w,v=a,z=d.overlay,E=e.queue(function(){a.src=e.EMPTY_PNG;b(!1,c)}),u=e.renderImageToCanvas,h=h-360*Math.floor(h/360);a._type=this.file.type;if(d.multipass)for(;2<p(C/n,r/t);)C=C/2+0.5|0,r=r/2+0.5|0,w=m.createElement("canvas"),w.width=C,w.height=r,v!==
a?(u(w,v,0,0,v.width,v.height,0,0,C,r),v=w):(v=w,u(v,a,d.sx,d.sy,d.sw,d.sh,0,0,C,r),d.sx=d.sy=d.sw=d.sh=0);c.width=h%180?t:n;c.height=h%180?n:t;c.type=d.type;c.quality=d.quality;g.rotate(h*Math.PI/180);u(g.canvas,v,d.sx,d.sy,d.sw||v.width,d.sh||v.height,180==h||270==h?-n:0,90==h||180==h?-t:0,n,t);n=c.width;t=c.height;z&&e.each([].concat(z),function(a){E.inc();var f=new window.Image,b=function(){var c=a.x|0,d=a.y|0,w=a.w||f.width,v=a.h||f.height,h=a.rel,c=1==h||4==h||7==h?(n-w+c)/2:2==h||5==h||8==
h?n-(w+c):c,d=3==h||4==h||5==h?(t-v+d)/2:6<=h?t-(v+d):d;e.event.off(f,"error load abort",b);try{g.globalAlpha=a.opacity||1,g.drawImage(f,c,d,w,v)}catch(s){}E.next()};e.event.on(f,"error load abort",b);f.src=a.src;f.complete&&b()});f&&(E.inc(),q.applyFilter(c,f,E.next));E.check()},getMatrix:function(a){var b=e.extend({},this.matrix),c=b.sw=b.sw||a.videoWidth||a.naturalWidth||a.width;a=b.sh=b.sh||a.videoHeight||a.naturalHeight||a.height;var d=b.dw=b.dw||c,g=b.dh=b.dh||a,h=c/a,n=d/g,t=b.resize;if("preview"==
t){if(d!=c||g!=a)if(n>=h?(h=c,t=h/n):(t=a,h=t*n),h!=c||t!=a)b.sx=~~((c-h)/2),b.sy=~~((a-t)/2),c=h,a=t}else t&&(c>d||a>g?"min"==t?(d=u(h<n?p(c,d):g*h),g=u(h<n?d/h:p(a,g))):(d=u(h>=n?p(c,d):g*h),g=u(h>=n?d/h:p(a,g))):(d=c,g=a));b.sw=c;b.sh=a;b.dw=d;b.dh=g;b.multipass=e.multiPassResize;return b},_trans:function(a){this._load(this.file,function(b,c){if(b)a(b);else try{this._apply(c,a)}catch(d){e.log("[err] FileAPI.Image.fn._apply:",d),a(d)}})},get:function(a){if(e.support.transform){var b=this,c=b.matrix;
"auto"==c.deg?e.getInfo(b.file,function(d,g){c.deg=h[g&&g.exif&&g.exif.Orientation]||0;b._trans(a)}):b._trans(a)}else a("not_support_transform");return this},toData:function(a){return this.get(a)}};q.exifOrientation=h;q.transform=function(a,b,g,d){function h(n,m){var t={},B=e.queue(function(a){d(a,t)});n?B.fail():e.each(b,function(b,f){if(!B.isFail()){var d=new q(m.nodeType?m:a);if("function"==typeof b)b(m,d);else if(b.width)d[b.preview?"preview":"resize"](b.width,b.height,b.strategy);else b.maxWidth&&
(m.width>b.maxWidth||m.height>b.maxHeight)&&d.resize(b.maxWidth,b.maxHeight,"max");if(b.crop){var e=b.crop;d.crop(e.x|0,e.y|0,e.w||e.width,e.h||e.height)}b.rotate===c&&g&&(b.rotate="auto");d.set({deg:b.rotate,type:b.type||a.type||"image/png",quality:b.quality||1,overlay:b.overlay,filter:b.filter});B.inc();d.toData(function(a,b){a?B.fail():(t[f]=b,B.next())})}})}a.width?h(!1,a):e.getInfo(a,h)};e.each(["TOP","CENTER","BOTTOM"],function(a,b){e.each(["LEFT","CENTER","RIGHT"],function(c,d){q[a+"_"+c]=
3*b+d;q[c+"_"+a]=3*b+d})});q.toCanvas=function(a){var b=m.createElement("canvas");b.width=a.videoWidth||a.width;b.height=a.videoHeight||a.height;b.getContext("2d").drawImage(a,0,0);return b};q.fromDataURL=function(a,b,c){a=e.newImage(a);e.extend(a,b);c(a)};q.applyFilter=function(a,b,c){"function"==typeof b?b(a,c):window.Caman&&window.Caman("IMG"==a.tagName?q.toCanvas(a):a,function(){if("string"==typeof b)this[b]();else e.each(b,function(a,b){this[b](a)},this);this.render(c)})};e.renderImageToCanvas=
function(a,b,c,d,g,h,n,t,m,r){try{return a.getContext("2d").drawImage(b,c,d,g,h,n,t,m,r)}catch(f){throw e.log("renderImageToCanvas failed:",f),f;}};e.support.canvas=e.support.transform=n;e.Image=q})(FileAPI,document);
(function(e){e(FileAPI)})(function(e){if(window.navigator&&window.navigator.platform&&/iP(hone|od|ad)/.test(window.navigator.platform)){var m=e.renderImageToCanvas;e.detectSubsampling=function(c){var e;return 1048576<c.width*c.height?(e=document.createElement("canvas"),e.width=e.height=1,e=e.getContext("2d"),e.drawImage(c,-c.width+1,0),0===e.getImageData(0,0,1,1).data[3]):!1};e.detectVerticalSquash=function(c,e){var m=c.naturalHeight||c.height,u=document.createElement("canvas"),n=u.getContext("2d"),
h,g,a;e&&(m/=2);u.width=1;u.height=m;n.drawImage(c,0,0);u=n.getImageData(0,0,1,m).data;n=0;for(g=h=m;g>n;)a=u[4*(g-1)+3],0===a?h=g:n=g,g=h+n>>1;return g/m||1};e.renderImageToCanvas=function(c,q,p,u,n,h,g,a,b,s){if("image/jpeg"===q._type){var d=c.getContext("2d"),B=document.createElement("canvas"),x=B.getContext("2d"),y,t;B.width=1024;B.height=1024;d.save();if(y=e.detectSubsampling(q))p/=2,u/=2,n/=2,h/=2;t=e.detectVerticalSquash(q,y);if(y||1!==t){u*=t;b=Math.ceil(1024*b/n);s=Math.ceil(1024*s/h/t);
for(t=a=0;t<h;){for(y=g=0;y<n;)x.clearRect(0,0,1024,1024),x.drawImage(q,p,u,n,h,-y,-t,n,h),d.drawImage(B,0,0,1024,1024,g,a,b,s),y+=1024,g+=b;t+=1024;a+=s}d.restore();return c}}return m(c,q,p,u,n,h,g,a,b,s)}}});
(function(e,m){function c(){this.items=[]}function q(c,a,b){var h=c.blob,d=c.file;if(d)if(h.toDataURL){var n={"image/jpeg":".jpe?g","image/png":".png"},m=n[c.type]?c.type:"image/png",n=n[m]||".png",q=h.quality||1;d.match(RegExp(n+"$","i"))||(d+=n.replace("?",""));c.file=d;c.type=m;!b&&h.toBlob?h.toBlob(function(b){a(c,b)},m,q):a(c,e.toBinaryString(h.toDataURL(m,q)))}else e.readAsBinaryString(h,function(b){"load"==b.type&&a(c,b.result)});else a(c,h)}var p=m.FormData,u=m.document,n=m.unescape,h=m.encodeURIComponent;
c.prototype={append:function(c,a,b,e){this.items.push({name:c,blob:a&&a.blob||(void 0==a?"":a),file:a&&(b||a.name),type:a&&(e||a.type)})},each:function(c){for(var a=0,b=this.items.length;a<b;a++)c.call(this,this.items[a])},toData:function(c,a){a._chunked=e.support.chunked&&0<a.chunkSize&&1==e.filter(this.items,function(a){return a.file}).length;e.support.html5?!e.formData||this.multipart||!p?(e.log("FileAPI.Form.toMultipartData"),this.toMultipartData(c)):a._chunked?(e.log("FileAPI.Form.toPlainData"),
this.toPlainData(c)):(e.log("FileAPI.Form.toFormData"),this.toFormData(c)):(e.log("FileAPI.Form.toHtmlData"),this.toHtmlData(c))},_to:function(c,a,b,h){var d=e.queue(function(){a(c)});this.each(function(a){b(a,c,d,h)});d.check()},toHtmlData:function(c){this._to(u.createDocumentFragment(),c,function(a,b){var c=a.blob,d;a.file?(e.reset(c,!0),c.name=a.name,b.appendChild(c)):(d=u.createElement("input"),d.name=a.name,d.type="hidden",d.value=c,b.appendChild(d))})},toPlainData:function(c){this._to({},c,
function(a,b,c){a.file&&(b.type=a.file);a.blob.toBlob?(c.inc(),q(a,function(a,e){b.name=a.name;b.file=e;b.size=e.length;b.type=a.type;c.next()})):a.file?(b.name=a.blob.name,b.file=a.blob,b.size=a.blob.size,b.type=a.type):(b.params||(b.params=[]),b.params.push(h(a.name)+"\x3d"+h(a.blob)));b.start=-1;b.end=b.file&&b.file.FileAPIReadPosition||-1;b.retry=0})},toFormData:function(c){this._to(new p,c,function(a,b,c){a.blob&&a.blob.toBlob?(c.inc(),q(a,function(a,e){b.append(a.name,e,a.file);c.next()})):
a.file?b.append(a.name,a.blob,a.file):b.append(a.name,a.blob);a.file&&b.append("_"+a.name,a.file)})},toMultipartData:function(c){this._to([],c,function(a,b,c,d){c.inc();q(a,function(a,e){b.push("--_"+d+'\r\nContent-Disposition: form-data; name\x3d"'+a.name+'"'+(a.file?'; filename\x3d"'+n(h(a.file))+'"':"")+(a.file?"\r\nContent-Type: "+(a.type||"application/octet-stream"):"")+"\r\n\r\n"+e+"\r\n");c.next()},!0)},e.expando)}};e.Form=c})(FileAPI,window);
(function(e,m){var c=m.F,q=e.document,p=function(e){var h=m.defer().progress(e.progress);this.uid=m.uid();this.xhr={abort:c,getResponseHeader:c,getAllResponseHeaders:c};this.defer=h;this.options=m.extend({upload:c,complete:c,withCredentials:m.withCredentials},e);this.done=this.success=h.done;this.fail=this.error=h.fail;this.notify=h.notify;this.progress=h.progress},u={"":1,XML:1,Text:1,Body:1};p.prototype={status:0,statusText:"",constructor:p,getResponseHeader:function(c){return this.xhr.getResponseHeader(c)},
getAllResponseHeaders:function(){return this.xhr.getAllResponseHeaders()||{}},end:function(n,h){var g=this,a=g.defer,b=g.options,s=200==n||201==n?!1:h||"unknown";g.end=g.abort=c;g.status=n;h&&(g.statusText=h);m.log("xhr.end:",n,h);s?a.reject(s,g,b):a.resolve(g,b);b.complete(s,g);g.xhr&&g.xhr.node&&setTimeout(function(){var a=g.xhr.node;try{a.parentNode.removeChild(a)}catch(b){}try{delete e[g.uid]}catch(c){}e[g.uid]=g.xhr.node=null},9)},abort:function(){this.end(0,"abort");this.xhr&&(this.xhr.aborted=
!0,this.xhr.abort())},send:function(c){var e=this,g=this.options;c.toData(function(a){g.upload(g,e);e._send.call(e,g,a)},g)},_send:function(c,h){var g=this,a,b=g.uid,s=c.url;m.log("XHR._send:",h);c.cache||(s+=(~s.indexOf("?")?"\x26":"?")+m.uid());if(h.nodeName){var d=c.jsonp,s=s.replace(/([a-z]+)=(\?)/i,"$1\x3d"+b);c.upload(c,g);a=q.createElement("div");a.innerHTML='\x3cform target\x3d"'+b+'" action\x3d"'+s+'" method\x3d"POST" enctype\x3d"multipart/form-data" style\x3d"position: absolute; top: -1000px; overflow: hidden; width: 1px; height: 1px;"\x3e\x3ciframe name\x3d"'+
b+'" src\x3d"javascript:false;"\x3e\x3c/iframe\x3e'+(d&&0>c.url.indexOf("\x3d?")?'\x3cinput value\x3d"'+b+'" name\x3d"'+d+'" type\x3d"hidden"/\x3e':"")+"\x3c/form\x3e";var d=a.getElementsByTagName("form")[0],p=a.getElementsByTagName("iframe")[0];d.appendChild(h);m.log(d.parentNode.innerHTML);q.body.appendChild(a);g.xhr.node=a;var x=function(a){if(~s.indexOf(a.origin))try{var c=m.parseJSON(a.data);c.id==b&&y(c.status,c.statusText,c.response)}catch(d){y(0,d.message)}},y=e[b]=function(c,d,h){g.readyState=
4;g.responseText=h;g.end(c,d);m.event.off(e,"message",x);e[b]=a=p=p.onload=null};g.xhr.abort=function(){try{p.stop?p.stop():p.contentWindow.stop?p.contentWindow.stop():p.contentWindow.document.execCommand("Stop")}catch(a){}y(0,"abort")};m.event.on(e,"message",x);p.onload=function(){try{var a=p.contentWindow,c=a.document,b=a.result||m.parseJSON(c.body.innerHTML);y(b.status,b.statusText,b.response)}catch(f){m.log("[transport.onload]",f)}};g.readyState=2;d.submit();d=null}else s=s.replace(/([a-z]+)=(\?)&?/i,
""),this.xhr&&this.xhr.aborted?m.log("Error: already aborted"):(h.params&&(s+=(0>s.indexOf("?")?"?":"\x26")+h.params.join("\x26")),a=g.xhr=m.getXHR(),a.open(c.type||"POST",s,!0),c.responseType&&(a.responseType=c.responseType),c.withCredentials&&(a.withCredentials="true"),(!c.headers||!c.headers["X-Requested-With"])&&a.setRequestHeader("X-Requested-With","XMLHttpRequest"),m.each(c.headers,function(c,b){a.setRequestHeader(b,c)}),c._chunked?(a.upload&&a.upload.addEventListener("progress",m.throttle(function(a){h.retry||
g.notify({type:a.type,total:h.size,loaded:h.start+a.loaded,totalSize:h.size},g,c)},100),!1),a.onreadystatechange=function(){var b=parseInt(a.getResponseHeader("X-Last-Known-Byte"),10);g.status=a.status;g.statusText=a.statusText;g.readyState=a.readyState;if(4==a.readyState){try{for(var d in u)g["response"+d]=a["response"+d]}catch(e){}a.onreadystatechange=null;!a.status||0<a.status-201?(m.log("Error: "+a.status),(!a.status&&!a.aborted||500==a.status||416==a.status)&&++h.retry<=c.chunkUploadRetry?(d=
a.status?0:m.chunkNetworkDownRetryTimeout,c.pause(h.file,c),m.log("X-Last-Known-Byte: "+b),b?h.end=b:(h.end=h.start-1,416==a.status&&(h.end-=c.chunkSize)),setTimeout(function(){g._send(c,h)},d)):g.end(a.status)):(h.retry=0,h.end==h.size-1?g.end(a.status):(m.log("X-Last-Known-Byte: "+b),b&&(h.end=b),h.file.FileAPIReadPosition=h.end,setTimeout(function(){g._send(c,h)},0)));a=null}},h.start=h.end+1,h.end=Math.max(Math.min(h.start+c.chunkSize,h.size)-1,h.start),d=h.file,d=(d.slice||d.mozSlice||d.webkitSlice).call(d,
h.start,h.end+1),h.size&&!d.size?setTimeout(function(){g.end(-1)}):(a.setRequestHeader("Content-Range","bytes "+h.start+"-"+h.end+"/"+h.size),a.setRequestHeader("Content-Disposition","attachment; filename\x3d"+encodeURIComponent(h.name)),a.setRequestHeader("Content-Type",h.type||"application/octet-stream"),a.send(d)),d=d=null):(a.upload&&(a.upload.addEventListener("progress",m.throttle(function(a){g.notify(a,g,c)},100),!1),m.event.on(a,"progress",function(a){g.notify(a,g,c)})),a.onreadystatechange=
function(){g.status=a.status;g.statusText=a.statusText;g.readyState=a.readyState;if(4==a.readyState){try{for(var b in u)g["response"+b]=a["response"+b]}catch(d){}a.onreadystatechange=null;!a.status||201<a.status?(m.log("Error: "+a.status),(!a.status&&!a.aborted||500==a.status)&&(c.retry||0)<c.uploadRetry?(c.retry=(c.retry||0)+1,b=m.networkDownRetryTimeout,c.pause(c.file,c),setTimeout(function(){g._send(c,h)},b)):g.end(a.status)):g.end(a.status);a=null}},m.isArray(h)?(a.setRequestHeader("Content-Type",
"multipart/form-data; boundary\x3d_"+m.expando),d=h.join("")+"--_"+m.expando+"--",a.sendAsBinary?a.sendAsBinary(d):(d=Array.prototype.map.call(d,function(a){return a.charCodeAt(0)&255}),a.send((new Uint8Array(d)).buffer))):a.send(h)))}};m.XHR=p})(window,FileAPI);
(function(e,m){var c=e.URL||e.webkitURL,q=e.document,p=e.navigator,u=p.getUserMedia||p.webkitGetUserMedia||p.mozGetUserMedia||p.msGetUserMedia,n=!!u;m.support.media=n;var h=function(a){this.video=a};h.prototype={isActive:function(){return!!this._active},start:function(a){var b=this,e=b.video,d,g,h=function(c){b._active=!c;clearTimeout(g);clearTimeout(d);a&&a(c,b)};u.call(p,{video:!0},function(a){b.stream=a;e.src=c.createObjectURL(a);d=setInterval(function(){var a=q.createElement("canvas"),c,b=!1;
try{c=a.getContext("2d"),c.drawImage(e,0,0,1,1),b=255!=c.getImageData(0,0,1,1).data[4]}catch(f){}b&&h(null)},1E3);g=setTimeout(function(){h("timeout")},5E3);e.play()},h)},stop:function(){try{this._active=!1,this.video.pause(),this.stream.stop()}catch(a){}},shot:function(){return new g(this.video)}};h.get=function(a){return new h(a.firstChild)};h.publish=function(a,c,g){"function"==typeof c&&(g=c,c={});c=m.extend({},{width:"100%",height:"100%",start:!0},c);a.jquery&&(a=a[0]);var d=function(d){d?g(d):
(d=h.get(a),c.start?d.start(g):g(null,d))};a.style.width=0<=c.width?c.width+"px":c.width;a.style.height=0<=c.height?c.height+"px":c.height;if(m.html5&&n){var p=q.createElement("video");p.style.width=0<=c.width?c.width+"px":c.width;p.style.height=0<=c.height?c.height+"px":c.height;e.jQuery?jQuery(a).empty():a.innerHTML="";a.appendChild(p);d()}else h.fallback(a,c,d)};h.fallback=function(a,c,e){e("not_support_camera")};var g=function(a){a=a.nodeName?m.Image.toCanvas(a):a;var c=m.Image(a);c.type="image/png";
c.width=a.width;c.height=a.height;c.size=4*a.width*a.height;return c};h.Shot=g;m.Camera=h})(window,FileAPI);
(function(e,m,c){var q=e.document,p=e.location,u=e.navigator,n=c.each;c.support.flash=function(){var h=u.mimeTypes,g=!1;if(u.plugins&&"object"==typeof u.plugins["Shockwave Flash"])g=u.plugins["Shockwave Flash"].description&&!(h&&h["application/x-shockwave-flash"]&&!h["application/x-shockwave-flash"].enabledPlugin);else try{g=!(!e.ActiveXObject||!new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))}catch(a){c.log("Flash -- does not supported.")}g&&/^file:/i.test(p)&&c.log("[warn] Flash does not work on `file:` protocol.");
return g}();c.support.flash&&(!c.html5||!c.support.html5||c.cors&&!c.support.cors||c.media&&!c.support.media)&&function(){function h(a){return('\x3cobject id\x3d"#id#" classid\x3d"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width\x3d"'+(a.width||"100%")+'" height\x3d"'+(a.height||"100%")+'"\x3e\x3cparam name\x3d"movie" value\x3d"#src#" /\x3e\x3cparam name\x3d"flashvars" value\x3d"#flashvars#" /\x3e\x3cparam name\x3d"swliveconnect" value\x3d"true" /\x3e\x3cparam name\x3d"allowscriptaccess" value\x3d"always" /\x3e\x3cparam name\x3d"allownetworking" value\x3d"all" /\x3e\x3cparam name\x3d"menu" value\x3d"false" /\x3e\x3cparam name\x3d"wmode" value\x3d"#wmode#" /\x3e\x3cembed flashvars\x3d"#flashvars#" swliveconnect\x3d"true" allownetworking\x3d"all" allowscriptaccess\x3d"always" name\x3d"#id#" src\x3d"#src#" width\x3d"'+
(a.width||"100%")+'" height\x3d"'+(a.height||"100%")+'" menu\x3d"false" wmode\x3d"transparent" type\x3d"application/x-shockwave-flash"\x3e\x3c/embed\x3e\x3c/object\x3e').replace(/#(\w+)#/ig,function(c,b){return a[b]})}function g(a,c){if(a&&a.style){var b,d;for(b in c){d=c[b];"number"==typeof d&&(d+="px");try{a.style[b]=d}catch(e){}}}}function a(a,c){n(c,function(c,b){var d=a[b];a[b]=function(){this.parent=d;return c.apply(this,arguments)}})}function b(a){var b=a.wid=c.uid();r._fn[b]=a;return"FileAPI.Flash._fn."+
b}function s(a){try{r._fn[a.wid]=null,delete r._fn[a.wid]}catch(c){}}function d(a,c){if(!C.test(a)){if(/^\.\//.test(a)||"/"!=a.charAt(0)){var b=p.pathname,b=b.substr(0,b.lastIndexOf("/"));a=(b+"/"+a).replace("/./","/")}"//"!=a.substr(0,2)&&(a="//"+p.host+a);C.test(a)||(a=p.protocol+a)}c&&(a+=(/\?/.test(a)?"\x26":"?")+c);return a}function B(a,e,v){var m,n=c.uid(),p=q.createElement("div"),t=10;for(m in a)p.setAttribute(m,a[m]),p[m]=a[m];g(p,a);a.width="100%";a.height="100%";p.innerHTML=h(c.extend({id:n,
src:d(c.flashImageUrl,"r\x3d"+c.uid()),wmode:"opaque",flashvars:"scale\x3d"+a.scale+"\x26callback\x3d"+b(function P(){s(P);if(0<--t)try{r.get(n).setImage(e)}catch(a){c.log('[err] FlashAPI.Preview.setImage -- can not set "base64":',a)}return!0})},a));v(!1,p);p=null}var x=c.uid(),y=0,t={},C=/^https?:/i,r={_fn:{},init:function(){var a=q.body&&q.body.firstChild;if(a){do if(1==a.nodeType){c.log("FlashAPI.state: awaiting");var b=q.createElement("div");b.id="_"+x;g(b,{top:1,right:1,width:5,height:5,position:"absolute",
zIndex:"1000000"});a.parentNode.insertBefore(b,a);r.publish(b,x);return}while(a=a.nextSibling)}10>y&&setTimeout(r.init,50*++y)},publish:function(a,b,e){e=e||{};a.innerHTML=h({id:b,src:d(c.flashUrl,"r\x3d"+c.version),wmode:e.camera?"":"transparent",flashvars:"callback\x3d"+(e.onEvent||"FileAPI.Flash.onEvent")+"\x26flashId\x3d"+b+"\x26storeKey\x3d"+u.userAgent.match(/\d/ig).join("")+"_"+c.version+(r.isReady||(c.pingUrl?"\x26ping\x3d"+c.pingUrl:""))+"\x26timeout\x3d"+c.flashAbortTimeout+(e.camera?"\x26useCamera\x3d"+
d(c.flashWebcamUrl):"")+"\x26debug\x3d"+(c.debug?"1":"")},e)},ready:function(){c.log("FlashAPI.state: ready");r.ready=c.F;r.isReady=!0;r.patch();r.patchCamera&&r.patchCamera();c.event.on(q,"mouseover",r.mouseover);c.event.on(q,"click",function(a){r.mouseover(a)&&(a.preventDefault?a.preventDefault():a.returnValue=!0)})},getEl:function(){return q.getElementById("_"+x)},getWrapper:function(a){do if(/js-fileapi-wrapper/.test(a.className))return a;while((a=a.parentNode)&&a!==q.body)},mouseover:function(a){a=
c.event.fix(a).target;if(/input/i.test(a.nodeName)&&"file"==a.type){var b=a.getAttribute(x),d=r.getWrapper(a);if(c.multiFlash){if("i"==b||"r"==b)return!1;if("p"!=b){a.setAttribute(x,"i");b=q.createElement("div");if(!d){c.log("[err] FlashAPI.mouseover: js-fileapi-wrapper not found");return}g(b,{top:0,left:0,width:a.offsetWidth+100,height:a.offsetHeight+100,zIndex:"1000000",position:"absolute"});d.appendChild(b);r.publish(b,c.uid());a.setAttribute(x,"p")}return!0}if(d){var b=d.getBoundingClientRect(),
h=q.body,d=(d&&d.ownerDocument).documentElement,d={top:b.top+(e.pageYOffset||d.scrollTop)-(d.clientTop||h.clientTop||0),left:b.left+(e.pageXOffset||d.scrollLeft)-(d.clientLeft||h.clientLeft||0),width:b.right-b.left,height:b.bottom-b.top};g(r.getEl(),d);r.curInp=a}}else/object|embed/i.test(a.nodeName)||g(r.getEl(),{top:1,left:1,width:5,height:5})},onEvent:function(a){var b=a.type;if("ready"==b){try{r.getInput(a.flashId).setAttribute(x,"r")}catch(d){}r.ready();setTimeout(function(){r.mouseenter(a)},
50);return!0}"ping"===b?c.log("(flash -\x3e js).ping:",[a.status,a.savedStatus],a.error):"log"===b?c.log("(flash -\x3e js).log:",a.target):b in r&&setTimeout(function(){c.log("FlashAPI.event."+a.type+":",a);r[b](a)},1)},mouseenter:function(a){var b=r.getInput(a.flashId);if(b){r.cmd(a,"multiple",null!=b.getAttribute("multiple"));var d=[],e={};n((b.getAttribute("accept")||"").split(/,\s*/),function(a){c.accept[a]&&n(c.accept[a].split(" "),function(a){e[a]=1})});n(e,function(a,c){d.push(c)});r.cmd(a,
"accept",d.length?d.join(",")+","+d.join(",").toUpperCase():"*")}},get:function(a){return q[a]||e[a]||q.embeds[a]},getInput:function(a){if(c.multiFlash)try{var b=r.getWrapper(r.get(a));if(b)return b.getElementsByTagName("input")[0]}catch(d){c.log('[err] Can not find "input" by flashId:',a,d)}else return r.curInp},select:function(a){var b=r.getInput(a.flashId),d=c.uid(b);a=a.target.files;n(a,function(a){a.type=c.getMimeType(a)});t[d]=a;q.createEvent?(d=q.createEvent("Event"),d.files=a,d.initEvent("change",
!0,!0),b.dispatchEvent(d)):m?m(b).trigger({type:"change",files:a}):(d=q.createEventObject(),d.files=a,b.fireEvent("onchange",d))},cmd:function(a,b,d,e){try{return c.log("(js -\x3e flash)."+b+":",d),r.get(a.flashId||a).cmd(b,d)}catch(g){c.log("(js -\x3e flash).onError:",g),e||setTimeout(function(){r.cmd(a,b,d,!0)},50)}},patch:function(){c.flashEngine=!0;a(c,{readAsDataURL:function(a,d){a&&!a.flashId?this.parent.apply(this,arguments):(c.log("FlashAPI.readAsBase64"),r.cmd(a,"readAsBase64",{id:a.id,callback:b(function z(b,
e){s(z);c.log("FlashAPI.readAsBase64:",b);d({type:b?"error":"load",error:b,result:"data:"+a.type+";base64,"+e})})}))},readAsText:function(a,b,d){d?c.log("[warn] FlashAPI.readAsText not supported `encoding` param"):d=b;c.readAsDataURL(a,function(a){if("load"==a.type)try{a.result=e.atob(a.result.split(";base64,")[1])}catch(c){a.type="error",a.error=c.toString()}d(a)})},getFiles:function(a,b,d){if(d)return c.filterFiles(c.getFiles(a),b,d),null;var e=c.isArray(a)?a:t[c.uid(a.target||a.srcElement||a)];
if(!e)return this.parent.apply(this,arguments);b&&(b=c.getFilesFilter(b),e=c.filter(e,function(a){return b.test(a.name)}));return e},getInfo:function(a,d){if(a&&!a.flashId)this.parent.apply(this,arguments);else if(a.isShot)d(null,a.info={width:a.width,height:a.height});else{if(!a.__info){var e=a.__info=c.defer();r.cmd(a,"getFileInfo",{id:a.id,callback:b(function E(c,b){s(E);e.resolve(c,a.info=b)})})}a.__info.then(d)}}});c.support.transform=!0;c.Image&&a(c.Image.prototype,{get:function(a,c){this.set({scaleMode:c||
"noScale"});return this.parent(a)},_load:function(a,b){c.log("FlashAPI.Image._load:",a);if(a&&!a.flashId)this.parent.apply(this,arguments);else{var d=this;c.getInfo(a,function(c){b.call(d,c,a)})}},_apply:function(a,d){c.log("FlashAPI.Image._apply:",a);if(a&&!a.flashId)this.parent.apply(this,arguments);else{var e=this.getMatrix(a.info),g=d;r.cmd(a,"imageTransform",{id:a.id,matrix:e,callback:b(function D(b,h){c.log("FlashAPI.Image._apply.callback:",b);s(D);b?g(b):!c.support.html5&&(!c.support.dataURI||
3E4<h.length)?B({width:e.deg%180?e.dh:e.dw,height:e.deg%180?e.dw:e.dh,scale:e.scaleMode},h,g):(e.filter&&(g=function(a,b){a?d(a):c.Image.applyFilter(b,e.filter,function(){d(a,this.canvas)})}),c.newImage("data:"+a.type+";base64,"+h,g))})})}},toData:function(a){var b=this.file,d=b.info,e=this.getMatrix(d);c.log("FlashAPI.Image.toData");b&&!b.flashId?this.parent.apply(this,arguments):("auto"==e.deg&&(e.deg=c.Image.exifOrientation[d&&d.exif&&d.exif.Orientation]||0),a.call(this,!b.info,{id:b.id,flashId:b.flashId,
name:b.name,type:b.type,matrix:e}))}});c.Image&&a(c.Image,{fromDataURL:function(a,b,d){!c.support.dataURI||3E4<a.length?B(c.extend({scale:"exactFit"},b),a.replace(/^data:[^,]+,/,""),function(a,c){d(c)}):this.parent(a,b,d)}});a(c.Form.prototype,{toData:function(a){for(var b=this.items,d=b.length;d--;)if(b[d].file&&b[d].blob&&!b[d].blob.flashId)return this.parent.apply(this,arguments);c.log("FlashAPI.Form.toData");a(b)}});a(c.XHR.prototype,{_send:function(a,e){if(e.nodeName||e.append&&c.support.html5||
c.isArray(e)&&"string"===typeof e[0])return this.parent.apply(this,arguments);var g={},h={},m=this,p,q;n(e,function(a){a.file?(h[a.name]=a={id:a.blob.id,name:a.blob.name,matrix:a.blob.matrix,flashId:a.blob.flashId},q=a.id,p=a.flashId):g[a.name]=a.blob});q||(p=x);if(p)c.log("FlashAPI.XHR._send: "+p+" -\x3e "+q);else return c.log("[err] FlashAPI._send: flashId -- undefined"),this.parent.apply(this,arguments);m.xhr={headers:{},abort:function(){r.cmd(p,"abort",{id:q})},getResponseHeader:function(a){return this.headers[a]},
getAllResponseHeaders:function(){return this.headers}};var t=c.queue(function(){r.cmd(p,"upload",{url:d(a.url.replace(/([a-z]+)=(\?)&?/i,"")),data:g,files:q?h:null,headers:a.headers||{},callback:b(function R(b){var d=b.type,e=b.result;c.log("FlashAPI.upload."+d);if("progress"==d)b.loaded=Math.min(b.loaded,b.total),b.lengthComputable=!0,a.progress(b);else if("complete"==d)s(R),"string"==typeof e&&(m.responseText=e.replace(/%22/g,'"').replace(/%5c/g,"\\").replace(/%26/g,"\x26").replace(/%25/g,"%")),
m.end(b.status||200);else if("abort"==d||"error"==d)m.end(b.status||0,b.message),s(R)})})});n(h,function(a){t.inc();c.getInfo(a,t.next)});t.check()}})}};r.wrap=b;r.unwrap=s;c.Flash=r;c.newImage("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw\x3d\x3d",function(a,b){c.support.dataURI=!(1!=b.width||1!=b.height);r.init()})}()})(window,window.jQuery,FileAPI);
(function(e,m,c){var q=c.each,p=c.extend,u=[],n=c.Flash,h=n.wrap,g=n.unwrap;c.support.flash&&(c.media&&!c.support.media)&&(c.extend(n,{patchCamera:function(){c.Camera.fallback=function(a,b,e){var d=c.uid();c.log("FlashAPI.Camera.publish: "+d);n.publish(a,d,p(b,{camera:!0,onEvent:h(function x(a){"camera"===a.type&&(g(x),a.error?(c.log("FlashAPI.Camera.publish.error: "+a.error),e(a.error)):(c.log("FlashAPI.Camera.publish.success: "+d),e(null)))})}))};q(u,function(a){c.Camera.fallback.apply(c.Camera,
a)});u=[];p(c.Camera.prototype,{_id:function(){return this.video.id},start:function(a){var b=this;n.cmd(this._id(),"camera.on",{callback:h(function d(e){g(d);e.error?(c.log("FlashAPI.camera.on.error: "+e.error),a(e.error,b)):(c.log("FlashAPI.camera.on.success: "+b._id()),b._active=!0,a(null,b))})})},stop:function(){this._active=!1;n.cmd(this._id(),"camera.off")},shot:function(){c.log("FlashAPI.Camera.shot:",this._id());var a=n.cmd(this._id(),"shot",{});a.type="image/png";a.flashId=this._id();a.isShot=
!0;return new c.Camera.Shot(a)}})}}),c.Camera.fallback=function(){u.push(arguments)})})(window,window.jQuery,FileAPI);"function"===typeof define&&define.amd&&define("FileAPI",[],function(){return FileAPI});