//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define(["dojo/_base/lang","dojo/_base/array","jimu/LayerInfos/LayerInfos","dojo/Deferred","dojo/promise/all"],function(c,g,m,f,d){function n(a){var b=[],h=[];g.forEach(a,function(a){0>b.indexOf(a.name)?b.push(a.name):h.push(a)});g.forEach(h,function(a){a.name=a.name+"-"+a.id})}var k={readLayerInfosObj:function(a){return m.getInstance(a,a.itemInfo)},readLayerInfosFromMap:function(a){var b=new f;m.getInstance(a,a.itemInfo).then(c.hitch(this,
function(a){var d=[];a.traversal(c.hitch(this,function(a){d.push(a)}));b.resolve(d)}),c.hitch(this,function(a){console.error(a);b.reject(a)}));return b},readLayerObjectsFromMap:function(a){var b=new f,h=[];this.readLayerInfosFromMap(a).then(c.hitch(this,function(a){g.forEach(a,c.hitch(this,function(a){h.push(a.getLayerObject())}));d(h).then(c.hitch(this,function(a){b.resolve(a)}),c.hitch(this,function(a){b.reject(a);console.error(a)}))}),c.hitch(this,function(a){b.reject(a)}));return b},readConfigLayerInfosFromMap:function(a){var b=
new f,h=[];this.readLayerInfosFromMap(a).then(c.hitch(this,function(a){var f=[];g.forEach(a,function(a){h.push(a.getLayerType())});d(h).then(c.hitch(this,function(d){g.forEach(d,c.hitch(this,function(b,d){"FeatureLayer"===b&&(a[d].name=a[d].title,f.push(a[d]))}));n(f);b.resolve(f)}),c.hitch(this,function(a){b.reject(a)}))}),c.hitch(this,function(a){b.reject(a)}));return b},getConfigInfosFromLayerInfos:function(a){return g.map(a,function(a){return k.getConfigInfoFromLayerInfo(a)})},getConfigInfoFromLayerInfo:function(a){var b=
{};b.name=a.name;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};if((a=a.getPopupInfo())&&!a.description)b.layer.fields=g.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label.toLowerCase(),show:a.visible}});return b}};return k})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"firstPage" class\x3d"first-page"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"tableEditInfosError" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv style\x3d"margin: 10px;" data-dojo-attach-point\x3d"exportcsv" checked \r\n          data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:15px; width: 100%; height: 100%;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .first-page{position: relative; height: 100%;}.jimu-widget-attributetable-setting .table-layer-infos{position: absolute; top: 0; bottom: 36px;}.jimu-widget-attributetable-setting .export-csv{margin: 10px; position: absolute; bottom: 0;}",
"*now":function(c){c(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/on dojo/Deferred dojo/dom-style jimu/dijit/SymbolChooser dojo/query dojo/aspect esri/symbols/jsonUtils jimu/dijit/Message esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol jimu/dijit/CheckBox jimu/dijit/LoadingShelter ../utils dijit/TooltipDialog dijit/popup".split(" "),function(c,g,m,f,d,n,k,a,b,h,p,w,x,q,y,z,A,B,t,r,
u,l){return c([m,g],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,tooltipDialogs:{},fieldTables:{},_allLayerFields:null,_layerInfos:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this.displayFieldsTable=new f({fields:[{name:"label",title:this.nls.label,type:"text"},{name:"url",title:"url",type:"text",hidden:!0},{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",actions:["edit"],
"class":"symbol"},{name:"show",title:this.nls.show,type:"checkbox","class":"show"}],selectable:!1,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);n.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.displayFieldsTable.startup();this.shelter=new t({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();this.own(k(this.displayFieldsTable,"actions-edit",d.hitch(this,this.editFieldsClick)));this.own(k(this.getParent().getParent().domNode,
"click",d.hitch(this,function(){l.close()})));n.addClass(this.exportcsv.domNode,"export-csv");this.setConfig(this.config)},editFieldsClick:function(a){var e=p(".action-item-parent",a);if(e&&e.length)if(e=this.displayFieldsTable.getRowData(a),e.show){var b=parseInt(e.index,10);this.shelter.show();this._getLayerFields(b).then(d.hitch(this,function(e){this.openFieldsDialog(a,e,b)}),d.hitch(this,function(a){console.error(a)})).always(d.hitch(this,function(){this.shelter.hide()}))}else var v=new q({message:this.nls.warning,
buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){v.close()})}]})},_getLayerFields:function(s){var e=new a,b=this._allLayerFields[s];b?e.resolve(b):this._layerInfos[s].getLayerObject().then(d.hitch(this,function(a){a.fields?e.resolve(a.fields):e.reject()}),d.hitch(this,function(a){e.reject(a)}));return e},openFieldsDialog:function(a,e,b){if(!this.tooltipDialogs[b]){var c=this._createFieldsTable(e,b);this.currentFieldTable=c;this.fieldTables[b]=c;e=new u({style:"width: 400px;height:400px;",
content:c.domNode,onClose:d.hitch(this,function(){this._allLayerFields[b]=c.getData()}),onCancel:d.hitch(this,function(){l.close()})});this.tooltipDialogs[b]=e}a=p(".row-edit-div",a)[0];l.open({parent:this,popup:this.tooltipDialogs[b],around:a,orient:["before-centered","below","below-alt","above","above-alt"]})},_createFieldsTable:function(a){for(var e=new f({fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show"},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",
title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!1,autoHeight:!1,style:{height:"400px",maxHeight:"400px"}}),b=0;b<a.length;b++)a[b].show=void 0===a[b].show?!0:!!a[b].show,e.addRow(a[b]);return e},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this.tooltipDialogs={};this._processTableData().then(d.hitch(this,function(a){this._init(a);this.shelter.hide()}),
d.hitch(this,function(a){new q({message:a.message||a})}))},_processTableData:function(){var b=new a;r.readConfigLayerInfosFromMap(this.map).then(d.hitch(this,function(a){this._layerInfos=a;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?b.resolve(this.config.layerInfos):b.resolve(r.getConfigInfosFromLayerInfos(a))}),d.hitch(this,function(a){console.error(a);b.reject(a)}));return b},_init:function(a){for(var e=0;e<a.length;e++)this.displayFieldsTable.addRow({label:a[e].name,url:a[e].layer.url,
index:""+e,show:a[e].show}),this._allLayerFields.push(a[e].layer.fields);0===a.length?(b.set(this.tableEditInfosError,"display",""),this.tableEditInfosError.innerHTML=this.nls.noLayers):b.set(this.tableEditInfosError,"display","none");this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check()},_destroyPopupDialog:function(){l.close();for(var a in this.tooltipDialogs)this.tooltipDialogs[a]&&this.tooltipDialogs[a].destroy&&(this.tooltipDialogs[a].destroy(),this.tooltipDialogs[a]=null)},
_getLayerInfoById:function(a){for(var b=0,d=this._layerInfos.length;b<d;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},getConfig:function(){l.close();for(var a=this.displayFieldsTable.getData(),b=[],d=a.length,c=0;c<d;c++){var f={};f.name=this._layerInfos[c].name;f.id=this._layerInfos[c].id;f.layer={};f.layer.url=a[c].url;f.layer.fields=this._allLayerFields[c];f.show=a[c].show;b.push(f)}this.config.layerInfos=b;this.exportcsv.getValue()?this.config.hideExportButton=!1:this.config.hideExportButton=
!0;return this.config},destroy:function(){this._destroyPopupDialog();this.inherited(arguments)}})});